// frontend/src/features/settings/send-mail.tsx
import { useEffect, useState } from 'react'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import DOMPurify from 'dompurify'
import { Bold, Code2, Italic, List, ListOrdered, Redo2, Send, Strikethrough, Undo2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Field } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { SettingsLayout } from '@/components/layout/settings-layout'
import { api } from '@/lib/api'
import { appStore, useAppStore } from '@/lib/store'
import { stringifyError } from '@/lib/utils'
import { useScopedI18n } from '@/i18n/react'

const emptyModel = { fromName: '', fromMail: '', toName: '', toMail: '', subject: '', contentType: 'text', content: '' }
const hasContent = (value: string, type: string) => {
  if (type === 'text') return value.replace(/[\u00AD\u200B-\u200D\u2060\uFEFF]/g, '').trim().length > 0
  const element = document.createElement('div'); element.innerHTML = value; element.querySelectorAll('script,style,noscript,template').forEach((node) => node.remove())
  return Boolean(element.textContent?.trim() || element.querySelector('img,audio,video,iframe,svg,canvas,table'))
}

export function SendMailPage({ admin = false, onSent }: { admin?: boolean; onSent?: () => void }) {
  const { t } = useScopedI18n(admin ? 'views.admin.SendMail' : 'views.index.SendMail')
  const { settings, model: storedModel, adminContact } = useAppStore((state) => ({ settings: state.settings, model: state.sendMailModel, adminContact: state.openSettings.adminContact }))
  const [model, setModel] = useState({ ...emptyModel, ...storedModel })
  const [preview, setPreview] = useState(false)
  const [sending, setSending] = useState(false)
  const editor = useEditor({ extensions: [StarterKit], content: model.content, onUpdate: ({ editor }) => update('content', editor.getHTML()), immediatelyRender: false })
  useEffect(() => { appStore.setState({ sendMailModel: model }) }, [model])
  useEffect(() => { if (editor && model.content !== editor.getHTML() && model.contentType === 'rich') editor.commands.setContent(model.content) }, [editor, model.contentType])
  const update = (key: string, value: any) => setModel((current) => ({ ...current, [key]: value }))
  const send = async () => {
    const subject = model.subject.trim(), to = model.toMail.trim()
    if (!subject) return toast.error(t('subjectEmpty'))
    if (!to) return toast.error(t('toMailEmpty'))
    if (!hasContent(model.content, model.contentType)) return toast.error(t('contentEmpty'))
    setSending(true)
    try {
      await api.fetch(admin ? '/api/admin/send_mail' : '/api/send_mail', { method: 'POST', body: { from_name: model.fromName, from_mail: admin ? (model.fromMail || '') : undefined, to_name: model.toName, to_mail: to, subject, is_html: model.contentType !== 'text', content: model.content } })
      setModel(emptyModel); setPreview(false); toast.success(t('successSend')); if (!admin) onSent?.()
    } catch (error) { toast.error(stringifyError(error)) } finally { setSending(false) }
  }
  const requestAccess = async () => { try { await api.fetch('/api/request_send_mail_access', { method: 'POST', body: {} }); await api.getSettings(); toast.success(t('success')) } catch (error) { toast.error(stringifyError(error)) } }
  if (!admin && (!settings.send_balance || settings.send_balance <= 0)) return <SettingsLayout><div className="rounded-md border border-border bg-muted/50 p-4 text-sm text-muted-foreground"><p>{t('requestAccessTip')}</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" onClick={requestAccess}>{t('requestAccess')}</Button>{adminContact && <Button variant="link" asChild><a href={adminContact}>{adminContact}</a></Button>}</div></div></SettingsLayout>
  const toolbar = editor && <div className="flex flex-wrap gap-1 border-b border-border p-1">{[
    [Bold, () => editor.chain().focus().toggleBold().run(), editor.isActive('bold')], [Italic, () => editor.chain().focus().toggleItalic().run(), editor.isActive('italic')], [Strikethrough, () => editor.chain().focus().toggleStrike().run(), editor.isActive('strike')], [Code2, () => editor.chain().focus().toggleCode().run(), editor.isActive('code')], [List, () => editor.chain().focus().toggleBulletList().run(), editor.isActive('bulletList')], [ListOrdered, () => editor.chain().focus().toggleOrderedList().run(), editor.isActive('orderedList')], [Undo2, () => editor.chain().focus().undo().run(), false], [Redo2, () => editor.chain().focus().redo().run(), false],
  ].map(([Icon, action, active], index) => { const C = Icon as any; return <Button key={index} type="button" size="icon" variant={active ? 'secondary' : 'ghost'} onClick={action as any}><C /></Button> })}</div>
  return <SettingsLayout action={<Button disabled={sending} onClick={send}><Send />{t('send')}</Button>}>
    {!admin && <p className="text-sm text-muted-foreground">{t('send_balance')}: <span className="numeric font-medium text-foreground">{settings.send_balance}</span></p>}
    <Field label={t('fromName')}><div className="grid gap-2 sm:grid-cols-2"><Input value={model.fromName} onChange={(event) => update('fromName', event.target.value)} />{admin ? <Input placeholder="sender@example.com" value={model.fromMail || ''} onChange={(event) => update('fromMail', event.target.value)} /> : <Input value={settings.address} disabled />}</div></Field>
    <Field label={t('toName')}><div className="grid gap-2 sm:grid-cols-2"><Input value={model.toName} onChange={(event) => update('toName', event.target.value)} /><Input type="email" value={model.toMail} onChange={(event) => update('toMail', event.target.value)} /></div></Field>
    <Field label={t('subject')}><Input value={model.subject} onChange={(event) => update('subject', event.target.value)} /></Field>
    <Field label={t('options')}><div className="flex flex-wrap items-center gap-2"><Tabs value={model.contentType} onValueChange={(value) => { update('contentType', value); setPreview(false) }}><TabsList className="rounded-md border border-border p-0.5"><TabsTrigger value="text">{t('text')}</TabsTrigger><TabsTrigger value="html">{t('html')}</TabsTrigger><TabsTrigger value="rich">{t('rich text')}</TabsTrigger></TabsList></Tabs>{model.contentType !== 'text' && <Button variant="secondary" onClick={() => setPreview((value) => !value)}>{preview ? t('edit') : t('preview')}</Button>}</div></Field>
    <Field label={t('content')}>{preview ? <div className="min-h-64 rounded-md border border-border p-4 mail-html" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(model.content) }} /> : model.contentType === 'rich' ? <div className="overflow-hidden rounded-md border border-input">{toolbar}<EditorContent editor={editor} className="min-h-[360px] px-4 py-3 [&_.tiptap]:min-h-[330px] [&_.tiptap]:outline-none" /></div> : <Textarea className="min-h-[360px] font-mono text-xs" value={model.content} onChange={(event) => update('content', event.target.value)} />}</Field>
  </SettingsLayout>
}

// frontend/src/views/admin/SendMail.vue
<script setup>
import '@wangeditor/editor/dist/css/style.css'
import { Editor, Toolbar } from '@wangeditor/editor-for-vue'
import { useScopedI18n } from '@/i18n/app'
import { onBeforeUnmount, ref, shallowRef } from 'vue'
import { useSessionStorage } from '@vueuse/core'
import { api } from '../../api'

const message = useMessage()
const isPreview = ref(false)
const editorRef = shallowRef()
const sending = ref(false)

const sendMailModel = useSessionStorage('sendMailByAdminModel', {
    fromName: "",
    fromMail: "",
    toName: "",
    toMail: "",
    subject: "",
    contentType: 'text',
    content: "",
});

const { t } = useScopedI18n('views.admin.SendMail')

const contentTypes = [
    { label: t('text'), value: 'text' },
    { label: t('html'), value: 'html' },
    { label: t('rich text'), value: 'rich' },
]

const normalizeSendMailText = (content) => {
    return content
        .replace(/[\u00AD\u200B-\u200D\u2060\uFEFF]/g, '')
        .replace(/\s+/g, ' ')
        .trim()
}

const hasSendMailContent = (content, contentType) => {
    if (typeof content !== 'string' || !content) {
        return false
    }

    if (contentType === 'text') {
        return normalizeSendMailText(content).length > 0
    }

    const container = document.createElement('div')
    container.innerHTML = content
    container.querySelectorAll('script, style, noscript, template').forEach((node) => node.remove())

    const plainContent = normalizeSendMailText(container.textContent ?? '')
    if (plainContent.length > 0) {
        return true
    }

    return Boolean(container.querySelector('img, audio, video, iframe, svg, canvas, table'))
}

const send = async () => {
    if (sending.value) {
        return
    }

    const fromMail = `${sendMailModel.value.fromMail ?? ''}`.trim()
    const toMail = `${sendMailModel.value.toMail ?? ''}`.trim()
    const subject = `${sendMailModel.value.subject ?? ''}`.trim()
    const content = `${sendMailModel.value.content ?? ''}`

    if (!fromMail) {
        message.error(t('fromMailEmpty'))
        return
    }
    if (!subject) {
        message.error(t('subjectEmpty'))
        return
    }
    if (!toMail) {
        message.error(t('toMailEmpty'))
        return
    }
    if (!hasSendMailContent(content, sendMailModel.value.contentType)) {
        message.error(t('contentEmpty'))
        return
    }

    const payload = {
        from_name: sendMailModel.value.fromName,
        from_mail: fromMail,
        to_name: sendMailModel.value.toName,
        to_mail: toMail,
        subject,
        is_html: sendMailModel.value.contentType != 'text',
        content,
    }

    sending.value = true
    try {
        await api.fetch(`/admin/send_mail`,
            {
                method: 'POST',
                body: JSON.stringify(payload)
            })
        sendMailModel.value = {
            fromName: "",
            fromMail: "",
            toName: "",
            toMail: "",
            subject: "",
            contentType: 'text',
            content: "",
        }
        message.success(t("successSend"));
    } catch (error) {
        message.error(error.message || "error");
    } finally {
        sending.value = false
    }
}

const toolbarConfig = {
    excludeKeys: ["uploadVideo"]
}

const editorConfig = {
    MENU_CONF: {
        'uploadImage': {
            async customUpload() {
                message.error(t('tooLarge'))
            },
            maxFileSize: 1 * 1024 * 1024,
            base64LimitSize: 1 * 1024 * 1024,
        }
    }
}

onBeforeUnmount(() => {
    const editor = editorRef.value
    if (editor == null) return
    editor.destroy()
})

const handleCreated = (editor) => {
    editorRef.value = editor;
}
</script>

<template>
    <div class="center">
        <n-card :bordered="false" embedded>
            <n-flex justify="end">
                <n-button type="primary" :loading="sending" :disabled="sending" @click="send">{{ t('send') }}</n-button>
            </n-flex>
            <div class="left">
                <n-form :model="sendMailModel">
                    <n-form-item :label="t('fromName')" label-placement="top">
                        <n-input-group>
                            <n-input v-model:value="sendMailModel.fromName" />
                            <n-input v-model:value="sendMailModel.fromMail" />
                        </n-input-group>
                    </n-form-item>
                    <n-form-item :label="t('toName')" label-placement="top">
                        <n-input-group>
                            <n-input v-model:value="sendMailModel.toName" />
                            <n-input v-model:value="sendMailModel.toMail" />
                        </n-input-group>
                    </n-form-item>
                    <n-form-item :label="t('subject')" label-placement="top">
                        <n-input v-model:value="sendMailModel.subject" />
                    </n-form-item>
                    <n-form-item :label="t('options')" label-placement="top">
                        <n-radio-group v-model:value="sendMailModel.contentType">
                            <n-radio-button v-for="option in contentTypes" :key="option.value" :value="option.value"
                                :label="option.label" />
                        </n-radio-group>
                        <n-button v-if="sendMailModel.contentType != 'text'" @click="isPreview = !isPreview"
                            style="margin-left: 10px;">
                            {{ isPreview ? t('edit') : t('preview') }}
                        </n-button>
                    </n-form-item>
                    <n-form-item :label="t('content')" label-placement="top">
                        <n-card :bordered="false" embedded v-if="isPreview">
                            <div v-html="sendMailModel.content" />
                        </n-card>
                        <div v-else-if="sendMailModel.contentType == 'rich'" class="rich-editor-shell">
                            <Toolbar class="rich-editor-toolbar" :defaultConfig="toolbarConfig"
                                :editor="editorRef" mode="default" />
                            <Editor style="height: 500px; overflow-y: hidden;" v-model="sendMailModel.content"
                                :defaultConfig="editorConfig" mode="default" @onCreated="handleCreated" />
                        </div>
                        <n-input v-else type="textarea" v-model:value="sendMailModel.content" :autosize="{
                            minRows: 3
                        }" />
                    </n-form-item>
                </n-form>
            </div>
        </n-card>
    </div>
</template>

<style scoped>
.n-card {
    max-width: 800px;
}

.n-button {
    text-align: left;
    margin-right: 10px;
}

.center {
    display: flex;
    text-align: center;
    place-items: center;
    justify-content: center;
}

.left {
    text-align: left;
    place-items: left;
    justify-content: left;
}
</style>
