// frontend/src/views/user/AddressManagement.vue
<script setup>
import { ref, h, onMounted } from 'vue';
import { useScopedI18n } from '@/i18n/app'
import { useRouter } from 'vue-router';
import { NBadge, NPopconfirm, NButton } from 'naive-ui'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import { getRouterPathWithLang } from '../../utils'

import Login from '../common/Login.vue';

const { jwt, workspaceSection } = useGlobalState()
const message = useMessage()
const router = useRouter()

const { locale, t } = useScopedI18n('views.user.AddressManagement')

const data = ref([])
const showTranferAddress = ref(false)
const currentAddress = ref("")
const currentAddressId = ref(0)
const targetUserEmail = ref('')

const changeMailAddress = async (address_id) => {
    try {
        const res = await api.fetch(`/user_api/bind_address_jwt/${address_id}`);
        message.success(t('changeMailAddress') + " " + t('success'));
        if (!res.jwt) {
            message.error("jwt not found");
            return;
        }
        jwt.value = res.jwt;
        workspaceSection.value = 'mail';
        await router.push(getRouterPathWithLang("/", locale.value))
        location.reload();
    } catch (error) {
        console.log(error)
        message.error(error.message || "error");
    }
}

const unbindAddress = async (address_id) => {
    try {
        const res = await api.fetch(`/user_api/unbind_address`, {
            method: 'POST',
            body: JSON.stringify({ address_id })
        });
        message.success(t('unbindAddress') + " " + t('success'));
        await fetchData();
    } catch (error) {
        console.log(error)
        message.error(error.message || "error");
    }
}

const transferAddress = async () => {
    if (!targetUserEmail.value) {
        message.error("targetUserEmail is required");
        return;
    }
    if (!currentAddressId.value) {
        message.error("currentAddressId is required");
        return;
    }
    try {
        const res = await api.fetch(`/user_api/transfer_address`, {
            method: 'POST',
            body: JSON.stringify({
                address_id: currentAddressId.value,
                target_user_email: targetUserEmail.value
            })
        });
        message.success(t('transferAddress') + " " + t('success'));
        await fetchData();
        showTranferAddress.value = false;
        currentAddressId.value = 0;
        currentAddress.value = "";
        targetUserEmail.value = "";
    } catch (error) {
        console.log(error)
        message.error(error.message || "error");
    }
}

const fetchData = async () => {
    try {
        const { results } = await api.fetch(
            `/user_api/bind_address`
        );
        data.value = results;
    } catch (error) {
        console.log(error)
        message.error(error.message || "error");
    }
}

const columns = [
    {
        title: t('name'),
        key: "name"
    },
    {
        title: t('mail_count'),
        key: "mail_count",
        render(row) {
            return h(NBadge, {
                value: row.mail_count,
                'show-zero': true,
                max: 99,
                type: "success"
            })
        }
    },
    {
        title: t('send_count'),
        key: "send_count",
        render(row) {
            return h(NBadge, {
                value: row.send_count,
                'show-zero': true,
                max: 99,
                type: "success"
            })
        }
    },
    {
        title: t('actions'),
        key: 'actions',
        render(row) {
            return h('div', [
                h(NPopconfirm,
                    {
                        onPositiveClick: () => changeMailAddress(row.id)
                    },
                    {
                        trigger: () => h(NButton,
                            {
                                tertiary: true,
                                type: "primary",
                            },
                            { default: () => t('changeMailAddress') }
                        ),
                        default: () => `${t('changeMailAddress')}?`
                    }
                ),
                h(NButton,
                    {
                        tertiary: true,
                        type: "primary",
                        onClick: () => {
                            currentAddressId.value = row.id;
                            currentAddress.value = row.name;
                            showTranferAddress.value = true;
                        }
                    },
                    { default: () => t('transferAddress') }
                ),
                h(NPopconfirm,
                    {
                        onPositiveClick: () => unbindAddress(row.id)
                    },
                    {
                        trigger: () => h(NButton,
                            {
                                tertiary: true,
                                type: "error",
                            },
                            { default: () => t('unbindAddress') }
                        ),
                        default: () => t('unbindAddressTip')
                    }
                ),
            ])
        }
    }
]

onMounted(async () => {
    await fetchData()
})
</script>

<template>
    <div>
        <n-modal v-model:show="showTranferAddress" preset="dialog" :title="t('transferAddress')">
            <span>
                <p>{{ t("transferAddressTip") }}</p>
                <p>{{ t('transferAddress') + ": " + currentAddress }}</p>
                <n-input v-model:value="targetUserEmail" :placeholder="t('targetUserEmail')" />
            </span>
            <template #action>
                <n-button :loading="loading" @click="transferAddress" size="small" tertiary type="error">
                    {{ t('transferAddress') }}
                </n-button>
            </template>
        </n-modal>
        <n-tabs type="segment">
            <n-tab-pane name="address" :tab="t('address')">
                <div class="address-table-scroll">
                    <n-data-table :columns="columns" :data="data" :bordered="false" embedded />
                </div>
            </n-tab-pane>
            <n-tab-pane name="create_or_bind" :tab="t('create_or_bind')">
                <Login />
            </n-tab-pane>
        </n-tabs>
    </div>
</template>

<style scoped>
.n-data-table {
    min-width: 640px;
}

.address-table-scroll {
    max-width: 100%;
    overflow-x: auto;
}
</style>

// frontend/src/features/user/address-management.tsx
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowRightLeft, Link2Off, MoveRight, Plus } from 'lucide-react'
import { toast } from 'sonner'
import { useNavigate } from 'react-router-dom'
import { confirmAction } from '@/components/action-dialogs'
import { AddressLogin } from '@/features/auth/address-login'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Field } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { api } from '@/lib/api'
import { appStore } from '@/lib/store'
import { stringifyError } from '@/lib/utils'
import { useScopedI18n } from '@/i18n/react'
import { getPathWithLocale } from '@/i18n/utils'

export function UserAddressManagement() {
  const { t, locale } = useScopedI18n('views.user.AddressManagement')
  const navigate = useNavigate()
  const query = useQuery({ queryKey: ['bound-addresses'], queryFn: () => api.fetch<{ results: any[] }>('/user_api/bind_address') })
  const [transfer, setTransfer] = useState<any>(null)
  const [target, setTarget] = useState('')
  const change = async (id: number) => { try { const result = await api.fetch<{ jwt: string }>(`/user_api/bind_address_jwt/${id}`); if (!result.jwt) throw new Error('jwt not found'); appStore.setState({ jwt: result.jwt, workspaceSection: 'mail' }); navigate(getPathWithLocale('/', locale)); location.reload() } catch (error) { toast.error(stringifyError(error)) } }
  const unbind = async (id: number) => { if (!(await confirmAction({ title: t('unbindAddress'), description: t('unbindAddressTip'), destructive: true }))) return; try { await api.fetch('/user_api/unbind_address', { method: 'POST', body: { address_id: id } }); await query.refetch(); toast.success(`${t('unbindAddress')} ${t('success')}`) } catch (error) { toast.error(stringifyError(error)) } }
  const transferAddress = async () => { if (!target || !transfer?.id) return; try { await api.fetch('/user_api/transfer_address', { method: 'POST', body: { address_id: transfer.id, target_user_email: target } }); await query.refetch(); setTransfer(null); setTarget(''); toast.success(`${t('transferAddress')} ${t('success')}`) } catch (error) { toast.error(stringifyError(error)) } }
  return <div className="h-full overflow-auto p-3 sm:p-5"><Tabs defaultValue="addresses"><TabsList className="mb-4 rounded-md border border-border p-0.5"><TabsTrigger value="addresses">{t('address')}</TabsTrigger><TabsTrigger value="create"><Plus />{t('create_or_bind')}</TabsTrigger></TabsList><TabsContent value="addresses"><Table><TableHeader><TableRow><TableHead>{t('name')}</TableHead><TableHead>{t('mail_count')}</TableHead><TableHead>{t('send_count')}</TableHead><TableHead className="w-[300px]">{t('actions')}</TableHead></TableRow></TableHeader><TableBody>{(query.data?.results || []).map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.name || row.address}</TableCell><TableCell><Badge>{row.mail_count || 0}</Badge></TableCell><TableCell><Badge>{row.send_count || 0}</Badge></TableCell><TableCell><div className="flex flex-wrap gap-1"><Button size="sm" variant="ghost" onClick={() => change(row.id)}><ArrowRightLeft />{t('changeMailAddress')}</Button><Button size="sm" variant="ghost" onClick={() => setTransfer(row)}><MoveRight />{t('transferAddress')}</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => unbind(row.id)}><Link2Off />{t('unbindAddress')}</Button></div></TableCell></TableRow>)}</TableBody></Table></TabsContent><TabsContent value="create" className="mx-auto max-w-xl py-3"><AddressLogin /></TabsContent></Tabs>
    <Dialog open={Boolean(transfer)} onOpenChange={(value) => !value && setTransfer(null)}><DialogContent><DialogHeader><DialogTitle>{t('transferAddress')}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{t('transferAddressTip')}</p><p className="text-sm font-medium">{transfer?.name || transfer?.address}</p><Field label={t('targetUserEmail')}><Input value={target} onChange={(event) => setTarget(event.target.value)} /></Field><DialogFooter><Button variant="destructive" onClick={transferAddress}><MoveRight />{t('transferAddress')}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
