// frontend/src/features/settings/account-settings.tsx
import { useState } from 'react'
import { DatabaseZap, KeyRound, LogOut, MailCheck, ShieldAlert, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Field } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { SettingsLayout } from '@/components/layout/settings-layout'
import { api } from '@/lib/api'
import { appStore, useAppStore } from '@/lib/store'
import { hashPassword, stringifyError } from '@/lib/utils'
import { useScopedI18n } from '@/i18n/react'
import { getPathWithLocale } from '@/i18n/utils'

export function AddressAccountSettings() {
  const { t, locale } = useScopedI18n('views.index.AccountSettings')
  const navigate = useNavigate()
  const { openSettings } = useAppStore((state) => ({ openSettings: state.openSettings }))
  const [confirmAction, setConfirmAction] = useState<null | 'logout' | 'delete' | 'inbox' | 'sent'>(null)
  const [passwordOpen, setPasswordOpen] = useState(false)
  const [password, setPassword] = useState('')
  const [confirmation, setConfirmation] = useState('')
  const run = async () => {
    try {
      if (confirmAction === 'logout') appStore.resetAddress()
      if (confirmAction === 'delete') { await api.fetch('/api/delete_address', { method: 'DELETE' }); appStore.resetAddress() }
      if (confirmAction === 'inbox') await api.fetch('/api/clear_inbox', { method: 'DELETE' })
      if (confirmAction === 'sent') await api.fetch('/api/clear_sent_items', { method: 'DELETE' })
      toast.success(t('success')); setConfirmAction(null)
      if (confirmAction === 'logout' || confirmAction === 'delete') navigate(getPathWithLocale('/', locale))
    } catch (error) { toast.error(stringifyError(error)) }
  }
  const changePassword = async () => {
    if (password !== confirmation) return toast.error(t('passwordMismatch'))
    try { await api.fetch('/api/address_change_password', { method: 'POST', body: { new_password: await hashPassword(password) } }); toast.success(t('passwordChanged')); setPassword(''); setConfirmation(''); setPasswordOpen(false) } catch (error) { toast.error(stringifyError(error)) }
  }
  const labels = { logout: [t('logout'), t('logoutConfirm')], delete: [t('deleteAccount'), t('deleteAccountConfirm')], inbox: [t('clearInbox'), t('clearInboxConfirm')], sent: [t('clearSentItems'), t('clearSentItemsConfirm')] } as const
  return <SettingsLayout>
    <div className="grid gap-2"><Button className="justify-start" variant="secondary" onClick={() => appStore.setState({ showAddressCredential: true })}><MailCheck />{t('showAddressCredential')}</Button>{openSettings.enableAddressPassword && <Button className="justify-start" variant="secondary" onClick={() => setPasswordOpen(true)}><KeyRound />{t('changePassword')}</Button>}{openSettings.enableUserDeleteEmail && <><Button className="justify-start" variant="secondary" onClick={() => setConfirmAction('inbox')}><DatabaseZap />{t('clearInbox')}</Button><Button className="justify-start" variant="secondary" onClick={() => setConfirmAction('sent')}><DatabaseZap />{t('clearSentItems')}</Button></>}<Button className="justify-start" variant="secondary" onClick={() => setConfirmAction('logout')}><LogOut />{t('logout')}</Button></div>
    {openSettings.enableUserDeleteEmail && <><Separator /><Button className="justify-start" variant="destructive" onClick={() => setConfirmAction('delete')}><Trash2 />{t('deleteAccount')}</Button></>}
    <Dialog open={Boolean(confirmAction)} onOpenChange={(value) => !value && setConfirmAction(null)}><DialogContent><DialogHeader><DialogTitle>{confirmAction && labels[confirmAction][0]}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{confirmAction && labels[confirmAction][1]}</p><DialogFooter><Button variant={confirmAction === 'delete' ? 'destructive' : 'default'} onClick={run}><ShieldAlert />{confirmAction && labels[confirmAction][0]}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={passwordOpen} onOpenChange={setPasswordOpen}><DialogContent><DialogHeader><DialogTitle>{t('changePassword')}</DialogTitle></DialogHeader><Field label={t('newPassword')}><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></Field><Field label={t('confirmPassword')}><Input type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></Field><DialogFooter><Button onClick={changePassword}><KeyRound />{t('changePassword')}</Button></DialogFooter></DialogContent></Dialog>
  </SettingsLayout>
}

// frontend/src/views/index/AccountSettings.vue
<script setup>
import { ref } from 'vue'
import { useScopedI18n } from '@/i18n/app'
import { useRouter } from 'vue-router'

import { useGlobalState } from '../../store'
import { api } from '../../api'
import { hashPassword } from '../../utils'
import { getRouterPathWithLang } from '../../utils'

const {
    jwt, settings, showAddressCredential, loading, openSettings
} = useGlobalState()
const router = useRouter()
const message = useMessage()

const showLogout = ref(false)
const showDeleteAccount = ref(false)
const showClearInbox = ref(false)
const showClearSentItems = ref(false)
const showChangePassword = ref(false)
const newPassword = ref('')
const confirmPassword = ref('')
const { locale, t } = useScopedI18n('views.index.AccountSettings')

const logout = async () => {
    jwt.value = '';
    await router.push(getRouterPathWithLang("/", locale.value))
    location.reload()
}

const deleteAccount = async () => {
    try {
        await api.fetch(`/api/delete_address`, {
            method: 'DELETE'
        });
        jwt.value = '';
        await router.push(getRouterPathWithLang("/", locale.value))
        location.reload()
    } catch (error) {
        message.error(error.message || "error");
    }
};

const clearInbox = async () => {
    try {
        await api.fetch(`/api/clear_inbox`, {
            method: 'DELETE'
        });
        message.success(t("success"));
    } catch (error) {
        message.error(error.message || "error");
    } finally {
        showClearInbox.value = false;
    }
};

const clearSentItems = async () => {
    try {
        await api.fetch(`/api/clear_sent_items`, {
            method: 'DELETE'
        });
        message.success(t("success"));
    } catch (error) {
        message.error(error.message || "error");
    } finally {
        showClearSentItems.value = false;
    }
};

const changePassword = async () => {
    if (newPassword.value !== confirmPassword.value) {
        message.error(t("passwordMismatch"));
        return;
    }
    try {
        await api.fetch(`/api/address_change_password`, {
            method: 'POST',
            body: JSON.stringify({
                new_password: await hashPassword(newPassword.value)
            })
        });
        message.success(t("passwordChanged"));
        newPassword.value = '';
        confirmPassword.value = '';
        showChangePassword.value = false;
    } catch (error) {
        message.error(error.message || "error");
    }
};
</script>

<template>
    <div class="center" v-if="settings.address">
        <n-card :bordered="false" embedded class="account-card settings-card">
            <n-button @click="showAddressCredential = true" type="primary" secondary block strong>
                {{ t('showAddressCredential') }}
            </n-button>
            <n-button v-if="openSettings?.enableAddressPassword" @click="showChangePassword = true" type="info" secondary block strong>
                {{ t('changePassword') }}
            </n-button>
            <n-button v-if="openSettings.enableUserDeleteEmail" @click="showClearInbox = true" type="warning" secondary
                block strong>
                {{ t('clearInbox') }}
            </n-button>
            <n-button v-if="openSettings.enableUserDeleteEmail" @click="showClearSentItems = true" type="warning"
                secondary block strong>
                {{ t('clearSentItems') }}
            </n-button>
            <n-button @click="showLogout = true" secondary block strong>
                {{ t('logout') }}
            </n-button>
            <n-divider v-if="openSettings.enableUserDeleteEmail" />
            <n-button v-if="openSettings.enableUserDeleteEmail" @click="showDeleteAccount = true" type="error" secondary
                block strong>
                {{ t('deleteAccount') }}
            </n-button>
        </n-card>

        <n-modal v-model:show="showLogout" preset="dialog" :title="t('logout')">
            <p>{{ t('logoutConfirm') }}</p>
            <template #action>
                <n-button :loading="loading" @click="logout" size="small" tertiary type="warning">
                    {{ t('logout') }}
                </n-button>
            </template>
        </n-modal>
        <n-modal v-model:show="showDeleteAccount" preset="dialog" :title="t('deleteAccount')">
            <p>{{ t('deleteAccountConfirm') }}</p>
            <template #action>
                <n-button :loading="loading" @click="deleteAccount" size="small" tertiary type="error">
                    {{ t('deleteAccount') }}
                </n-button>
            </template>
        </n-modal>
        <n-modal v-model:show="showClearInbox" preset="dialog" :title="t('clearInbox')">
            <p>{{ t('clearInboxConfirm') }}</p>
            <template #action>
                <n-button :loading="loading" @click="clearInbox" size="small" tertiary type="warning">
                    {{ t('clearInbox') }}
                </n-button>
            </template>
        </n-modal>
        <n-modal v-model:show="showClearSentItems" preset="dialog" :title="t('clearSentItems')">
            <p>{{ t('clearSentItemsConfirm') }}</p>
            <template #action>
                <n-button :loading="loading" @click="clearSentItems" size="small" tertiary type="warning">
                    {{ t('clearSentItems') }}
                </n-button>
            </template>
        </n-modal>
        
        <n-modal v-model:show="showChangePassword" preset="dialog" :title="t('changePassword')">
            <n-form :model="{ newPassword, confirmPassword }">
                <n-form-item :label="t('newPassword')">
                    <n-input v-model:value="newPassword" type="password" placeholder="" show-password-on="click"
                        @keyup.enter="changePassword" />
                </n-form-item>
                <n-form-item :label="t('confirmPassword')">
                    <n-input v-model:value="confirmPassword" type="password" placeholder="" show-password-on="click"
                        @keyup.enter="changePassword" />
                </n-form-item>
            </n-form>
            <template #action>
                <n-button :loading="loading" @click="changePassword" size="small" tertiary type="info">
                    {{ t('changePassword') }}
                </n-button>
            </template>
        </n-modal>
    </div>
</template>

<style scoped>
.center {
    display: flex;
    justify-content: center;
}

.account-card {
    max-width: 800px;
    text-align: left;
}

.n-button {
    margin-top: 14px;
}

</style>
