// frontend/src/views/common/Appearance.vue
<script setup>
import { useScopedI18n } from '@/i18n/app'

import { useIsMobile } from '../../utils/composables'
import { useGlobalState } from '../../store'
const props = defineProps({
    showUseSimpleIndex: {
        type: Boolean,
        default: false
    }
})

const {
    mailboxSplitSize, mailListView, mailListPreviewLineClamp, useIframeShowMail, preferShowTextMail, configAutoRefreshInterval,
    useSideMargin, useUTCDate, useSimpleIndex
} = useGlobalState()
const isMobile = useIsMobile()

const { t } = useScopedI18n('views.common.Appearance')
</script>

<template>
    <div class="center settings-page">
        <n-card class="settings-card" :bordered="false" embedded>
            <n-form-item-row v-if="!isMobile" :label="t('mailboxSplitSize')">
                <n-slider v-model:value="mailboxSplitSize" :min="0" :max="0.75" :step="0.01" :marks="{
                    0: '0',
                    0.25: '0.25',
                    0.5: '0.5',
                    0.75: '0.75'
                }" />
            </n-form-item-row>
            <n-form-item-row v-if="!isMobile" :label="t('mailListView')">
                <n-switch v-model:value="mailListView" :round="false" />
            </n-form-item-row>
            <n-form-item-row v-if="!isMobile" :label="t('mailListPreviewLineClamp')">
                <n-slider v-model:value="mailListPreviewLineClamp" :min="0" :max="5" :step="1" :marks="{
                    0: t('off'),
                    1: '1',
                    2: '2',
                    3: '3',
                    4: '4',
                    5: '5'
                }" />
            </n-form-item-row>
            <n-form-item-row :label="t('autoRefreshInterval')">
                <n-slider v-model:value="configAutoRefreshInterval" :min="30" :max="300" :step="1" :marks="{
                    60: '60', 120: '120', 180: '180', 240: '240'
                }" />
            </n-form-item-row>
            <n-form-item-row v-if="props.showUseSimpleIndex" :label="t('useSimpleIndex')">
                <n-switch v-model:value="useSimpleIndex" :round="false" />
            </n-form-item-row>
            <n-form-item-row :label="t('preferShowTextMail')">
                <n-switch v-model:value="preferShowTextMail" :round="false" />
            </n-form-item-row>
            <n-form-item-row :label="t('useIframeShowMail')">
                <n-switch v-model:value="useIframeShowMail" :round="false" />
            </n-form-item-row>
            <n-form-item-row :label="t('useUTCDate')">
                <n-switch v-model:value="useUTCDate" :round="false" />
            </n-form-item-row>
            <n-form-item-row v-if="!isMobile" :label="t('useSideMargin')">
                <n-switch v-model:value="useSideMargin" :round="false" />
            </n-form-item-row>
        </n-card>
    </div>
</template>

<style scoped>
.center {
    display: flex;
    justify-content: center;
}


.n-card {
    max-width: 800px;
    text-align: left;
}
</style>

// frontend/src/features/settings/appearance.tsx
import { Slider } from '@/components/ui/slider'
import { Switch } from '@/components/ui/switch'
import { SettingRow, SettingsLayout } from '@/components/layout/settings-layout'
import { appStore, useAppStore } from '@/lib/store'
import { useScopedI18n } from '@/i18n/react'

export function AppearanceSettings({ showSimpleIndex = false }: { showSimpleIndex?: boolean }) {
  const { t } = useScopedI18n('views.common.Appearance')
  const state = useAppStore((value) => value)
  return <SettingsLayout>
    <div className="hidden md:contents"><SettingRow label={t('mailboxSplitSize')} control={<div className="grid gap-2"><Slider min={0} max={0.75} step={0.01} value={[state.mailboxSplitSize]} onValueChange={([value]) => appStore.setState({ mailboxSplitSize: value })} /><span className="numeric text-xs text-muted-foreground">{state.mailboxSplitSize.toFixed(2)}</span></div>} /><SettingRow label={t('mailListView')} control={<Switch checked={state.mailListView} onCheckedChange={(value) => appStore.setState({ mailListView: value })} />} /><SettingRow label={t('mailListPreviewLineClamp')} control={<div className="grid gap-2"><Slider min={0} max={5} step={1} value={[state.mailListPreviewLineClamp]} onValueChange={([value]) => appStore.setState({ mailListPreviewLineClamp: value })} /><span className="numeric text-xs text-muted-foreground">{state.mailListPreviewLineClamp || t('off')}</span></div>} /></div>
    <SettingRow label={t('autoRefreshInterval')} control={<div className="grid gap-2"><Slider min={30} max={300} step={1} value={[state.configAutoRefreshInterval]} onValueChange={([value]) => appStore.setState({ configAutoRefreshInterval: value })} /><span className="numeric text-xs text-muted-foreground">{state.configAutoRefreshInterval}s</span></div>} />
    {showSimpleIndex && <SettingRow label={t('useSimpleIndex')} control={<Switch checked={state.useSimpleIndex} onCheckedChange={(value) => appStore.setState({ useSimpleIndex: value })} />} />}
    <SettingRow label={t('preferShowTextMail')} control={<Switch checked={state.preferShowTextMail} onCheckedChange={(value) => appStore.setState({ preferShowTextMail: value })} />} />
    <SettingRow label={t('useIframeShowMail')} control={<Switch checked={state.useIframeShowMail} onCheckedChange={(value) => appStore.setState({ useIframeShowMail: value })} />} />
    <SettingRow label={t('useUTCDate')} control={<Switch checked={state.useUTCDate} onCheckedChange={(value) => appStore.setState({ useUTCDate: value })} />} />
    <div className="hidden md:contents"><SettingRow label={t('useSideMargin')} control={<Switch checked={state.useSideMargin} onCheckedChange={(value) => appStore.setState({ useSideMargin: value })} />} /></div>
  </SettingsLayout>
}
