// frontend/src/components/MailBox.vue
<script setup>
import { watch, onMounted, ref, onBeforeUnmount, computed } from "vue";
import { useMessage } from 'naive-ui'
import { useScopedI18n } from '@/i18n/app'
import { useGlobalState } from '../store'
import { CloudDownloadRound, ArrowBackIosNewFilled, ArrowForwardIosFilled, InboxRound } from '@vicons/material'
import { useIsMobile } from '../utils/composables'
import { processItem } from '../utils/email-parser'
import { utcToLocalDate } from '../utils';
import { buildReplyModel, buildForwardModel } from '../utils/mail-actions'
import MailContentRenderer from "./MailContentRenderer.vue";
import AiExtractInfo from "./AiExtractInfo.vue";

const message = useMessage()
const isMobile = useIsMobile()

const props = defineProps({
  enableUserDeleteEmail: {
    type: Boolean,
    default: false,
    required: false
  },
  showEMailTo: {
    type: Boolean,
    default: true,
    required: false
  },
  fetchMailData: {
    type: Function,
    default: () => { },
    required: true
  },
  deleteMail: {
    type: Function,
    default: () => { },
    required: false
  },
  showReply: {
    type: Boolean,
    default: false,
    required: false
  },
  showSaveS3: {
    type: Boolean,
    default: false,
    required: false
  },
  saveToS3: {
    type: Function,
    default: (mail_id, filename, blob) => { },
    required: false
  },
  showFilterInput: {
    type: Boolean,
    default: false,
    required: false
  },
})

const localFilterKeyword = ref('')

const {
  isDark, mailboxSplitSize, mailListView, mailListPreviewLineClamp, indexTab, loading, useUTCDate,
  autoRefresh, configAutoRefreshInterval, sendMailModel
} = useGlobalState()
const autoRefreshInterval = ref(configAutoRefreshInterval.value)
const rawData = ref([])
const timer = ref(null)

const count = ref(0)
const page = ref(1)
const pageSize = ref(20)

const mailListPreviewLineClampValue = computed(() => {
  const value = Number(mailListPreviewLineClamp.value)
  if (!Number.isFinite(value)) return 0
  return Math.min(5, Math.max(0, Math.round(value)))
})

// Computed property for filtered data (only filter current page)
const data = computed(() => {
  if (!localFilterKeyword.value || localFilterKeyword.value.trim() === '') {
    return rawData.value;
  }
  const keyword = localFilterKeyword.value.toLowerCase();
  return rawData.value.filter(mail => {
    // Search in subject, text, message fields
    const searchFields = [
      mail.subject || '',
      mail.text || '',
      mail.message || ''
    ].map(field => field.toLowerCase());
    return searchFields.some(field => field.includes(keyword));
  });
})

const canGoPrevMail = computed(() => {
  if (!curMail.value) return false
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)
  return currentIndex > 0 || page.value > 1
})

const canGoNextMail = computed(() => {
  if (!curMail.value) return false
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)
  return currentIndex < data.value.length - 1 || count.value > page.value * pageSize.value
})

const prevMail = async () => {
  if (!canGoPrevMail.value) return
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)

  if (currentIndex > 0) {
    curMail.value = data.value[currentIndex - 1]
  } else if (page.value > 1) {
    page.value--
    await refresh()
    if (data.value.length > 0) {
      curMail.value = data.value[data.value.length - 1]
    }
  }
}

const nextMail = async () => {
  if (!canGoNextMail.value) return
  const currentIndex = data.value.findIndex(mail => mail.id === curMail.value.id)

  if (currentIndex < data.value.length - 1) {
    curMail.value = data.value[currentIndex + 1]
  } else if (count.value > page.value * pageSize.value) {
    page.value++
    await refresh()
    if (data.value.length > 0) {
      curMail.value = data.value[0]
    }
  }
}

const curMail = ref(null);

const multiActionMode = ref(false)
const showMultiActionDownload = ref(false)
const showMultiActionDelete = ref(false)
const multiActionDownloadZip = ref({})
const multiActionDeleteProgress = ref({ percentage: 0, tip: '0/0' })

const { t } = useScopedI18n('components.MailBox')

const setupAutoRefresh = async (autoRefresh) => {
  // auto refresh every configAutoRefreshInterval seconds
  autoRefreshInterval.value = configAutoRefreshInterval.value;
  if (autoRefresh) {
    clearInterval(timer.value);
    timer.value = setInterval(async () => {
      if (loading.value) return;
      autoRefreshInterval.value--;
      if (autoRefreshInterval.value <= 0) {
        autoRefreshInterval.value = configAutoRefreshInterval.value;
        await backFirstPageAndRefresh();
      }
    }, 1000)
  } else {
    clearInterval(timer.value)
    timer.value = null
  }
}

watch(autoRefresh, async (autoRefresh, old) => {
  setupAutoRefresh(autoRefresh)
}, { immediate: true })

watch([page, pageSize], async ([page, pageSize], [oldPage, oldPageSize]) => {
  if (page !== oldPage || pageSize !== oldPageSize) {
    await refresh();
  }
})

const refresh = async () => {
  try {
    const { results, count: totalCount } = await props.fetchMailData(
      pageSize.value, (page.value - 1) * pageSize.value
    );
    loading.value = true;
    rawData.value = await Promise.all(results.map(async (item) => {
      item.checked = false;
      return await processItem(item);
    }));
    if (totalCount > 0) {
      count.value = totalCount;
    }
    curMail.value = null;
    if (!isMobile.value && !mailListView.value && data.value.length > 0) {
      curMail.value = data.value[0];
    }
  } catch (error) {
    message.error(error.message || "error");
    console.error(error);
  } finally {
    loading.value = false;
  }
};

const backFirstPageAndRefresh = async () => {
  page.value = 1;
  await refresh();
}

const clickRow = async (row) => {
  if (multiActionMode.value) {
    row.checked = !row.checked;
    curMail.value = row;
    return;
  }
  if (mailListView.value && curMail.value?.id === row.id) {
    curMail.value = null;
    return;
  }
  curMail.value = row;
};


const mailItemClass = (row) => {
  return curMail.value && row.id == curMail.value.id ? (isDark.value ? 'overlay overlay-dark-backgroud' : 'overlay overlay-light-backgroud') : '';
};

const deleteMail = async () => {
  try {
    await props.deleteMail(curMail.value.id);
    message.success(t("success"));
    curMail.value = null;
    await refresh();
  } catch (error) {
    message.error(error.message || "error");
  }
};

const replyMail = async () => {
  Object.assign(sendMailModel.value, buildReplyModel(curMail.value, t('reply')));
  indexTab.value = 'sendmail';
};

const forwardMail = async () => {
  Object.assign(sendMailModel.value, buildForwardModel(curMail.value, t('forwardMail')));
  indexTab.value = 'sendmail';
};

const onSpiltSizeChange = (size) => {
  mailboxSplitSize.value = size;
}

const saveToS3Proxy = async (filename, blob) => {
  await props.saveToS3(curMail.value.id, filename, blob);
}

const multiActionModeClick = (enableMulti) => {
  if (enableMulti) {
    data.value.forEach((item) => {
      item.checked = false;
    });
    multiActionMode.value = true;
  } else {
    multiActionMode.value = false;
    data.value.forEach((item) => {
      item.checked = false;
    });
  }
}

const multiActionSelectAll = (checked) => {
  data.value.forEach((item) => {
    item.checked = checked;
  });
}

const multiActionDeleteMail = async () => {
  try {
    loading.value = true;
    const selectedMails = data.value.filter((item) => item.checked);
    if (selectedMails.length === 0) {
      message.error(t('pleaseSelectMail'));
      return;
    }
    multiActionDeleteProgress.value = {
      percentage: 0,
      tip: `0/${selectedMails.length}`
    };
    for (const [index, mail] of selectedMails.entries()) {
      await props.deleteMail(mail.id);
      showMultiActionDelete.value = true;
      multiActionDeleteProgress.value = {
        percentage: Math.floor((index + 1) / selectedMails.length * 100),
        tip: `${index + 1}/${selectedMails.length}`
      };
    }
    message.success(t("success"));
    await refresh();
  } catch (error) {
    message.error(error.message || "error");
  } finally {
    loading.value = false;
    showMultiActionDelete.value = true;
  }
}

const multiActionDownload = async () => {
  try {
    loading.value = true;
    const selectedMails = data.value.filter((item) => item.checked);
    if (selectedMails.length === 0) {
      message.error(t('pleaseSelectMail'));
      return;
    }
    const JSZipModlue = await import('jszip');
    const JSZip = JSZipModlue.default;
    const zip = new JSZip();
    for (const mail of selectedMails) {
      zip.file(`${mail.id}.eml`, mail.raw);
    }
    multiActionDownloadZip.value = {
      url: URL.createObjectURL(await zip.generateAsync({ type: "blob" })),
      filename: `mails-${new Date().toISOString().replace(/:/g, '-')}.zip`
    }
    showMultiActionDownload.value = true;
  } catch (error) {
    message.error(error.message || "error");
  } finally {
    loading.value = false;
  }
}

onMounted(async () => {
  await refresh();
});

onBeforeUnmount(() => {
  clearInterval(timer.value)
})
</script>

<template>
  <section class="mailbox">
    <div v-if="!isMobile" class="mailbox-desktop">
      <div class="mailbox-toolbar">
        <n-space v-if="multiActionMode" class="mailbox-toolbar__group" align="center">
          <n-button @click="multiActionModeClick(false)" tertiary>
            {{ t('cancelMultiAction') }}
          </n-button>
          <n-button @click="multiActionSelectAll(true)" tertiary>
            {{ t('selectAll') }}
          </n-button>
          <n-button @click="multiActionSelectAll(false)" tertiary>
            {{ t('unselectAll') }}
          </n-button>
          <n-popconfirm v-if="enableUserDeleteEmail" @positive-click="multiActionDeleteMail">
            <template #trigger>
              <n-button tertiary type="error">{{ t('delete') }}</n-button>
            </template>
            {{ t('deleteMailTip') }}
          </n-popconfirm>
          <n-button @click="multiActionDownload" tertiary type="info">
            <template #icon>
              <n-icon :component="CloudDownloadRound" />
            </template>
            {{ t('downloadMail') }}
          </n-button>
        </n-space>
        <n-space v-else class="mailbox-toolbar__group" align="center">
          <n-button @click="multiActionModeClick(true)" type="primary" tertiary>
            {{ t('multiAction') }}
          </n-button>
          <n-pagination v-model:page="page" v-model:page-size="pageSize" :item-count="count" :page-sizes="[20, 50, 100]"
            show-size-picker />
          <n-switch v-model:value="autoRefresh" :round="false">
            <template #checked>
              {{ t('refreshAfter', { msg: autoRefreshInterval }) }}
            </template>
            <template #unchecked>
              {{ t('autoRefresh') }}
            </template>
          </n-switch>
          <n-button @click="backFirstPageAndRefresh" type="primary" tertiary>
            {{ t('refresh') }}
          </n-button>
          <n-input v-if="showFilterInput" v-model:value="localFilterKeyword" class="mailbox-search"
            :placeholder="t('keywordQueryTip')" clearable />
        </n-space>
      </div>
      <n-split class="mailbox-split" direction="horizontal" :max="0.75" :min="0" :resize-trigger-size="8"
        :default-size="mailboxSplitSize" :on-update:size="onSpiltSizeChange" v-if="!mailListView || curMail">
        <template #resize-trigger>
          <div class="split-handle">
            <div class="split-handle__grip" />
          </div>
        </template>
        <template #1>
          <div class="mailbox-list-pane">
            <n-list class="mailbox-list" hoverable clickable>
              <n-list-item v-for="row in data" v-bind:key="row.id" @click="() => clickRow(row)"
                :class="['mailbox-row', mailItemClass(row)]">
                <template #prefix v-if="multiActionMode">
                  <n-checkbox v-model:checked="row.checked" />
                </template>
                <n-thing class="mailbox-row__content">
                  <template #header>
                    <n-ellipsis class="mailbox-row__subject">{{ row.subject }}</n-ellipsis>
                  </template>
                  <template #header-extra>
                    <span class="mailbox-row__date">{{ utcToLocalDate(row.created_at, useUTCDate) }}</span>
                  </template>
                  <template #description>
                    <div class="mailbox-row__meta">
                      <span class="mailbox-row__sender">
                        <n-ellipsis>
                        {{ showEMailTo ? "FROM: " + row.source : row.source }}
                        </n-ellipsis>
                      </span>
                      <span class="mailbox-row__id">#{{ row.id }}</span>
                      <span v-if="showEMailTo" class="mailbox-row__recipient">
                        <n-ellipsis>TO: {{ row.address }}</n-ellipsis>
                      </span>
                      <AiExtractInfo :metadata="row.metadata" compact />
                    </div>
                  </template>
                </n-thing>
              </n-list-item>
            </n-list>
          </div>
        </template>
        <template #2>
          <div v-if="curMail" class="mailbox-detail-nav">
            <n-flex justify="space-between" align="center">
              <n-space :wrap="false" align="center">
                <n-button v-if="mailListView" @click="curMail = null" text size="small">
                  <template #icon>
                    <n-icon>
                      <ArrowBackIosNewFilled />
                    </n-icon>
                  </template>
                  {{ t('backToList') }}
                </n-button>
                <n-button @click="prevMail" :disabled="!canGoPrevMail" text size="small">
                  <template #icon>
                    <n-icon>
                      <ArrowBackIosNewFilled />
                    </n-icon>
                  </template>
                  {{ t('prevMail') }}
                </n-button>
              </n-space>
              <n-button @click="nextMail" :disabled="!canGoNextMail" text size="small" icon-placement="right">
                <template #icon>
                  <n-icon>
                    <ArrowForwardIosFilled />
                  </n-icon>
                </template>
                {{ t('nextMail') }}
              </n-button>
            </n-flex>
          </div>
          <n-card :bordered="false" embedded v-if="curMail" class="mail-item mailbox-detail-card"
            :title="curMail.subject">
            <MailContentRenderer :mail="curMail" :showEMailTo="showEMailTo"
              :enableUserDeleteEmail="enableUserDeleteEmail" :showReply="showReply" :showSaveS3="showSaveS3"
              :onDelete="deleteMail" :onReply="replyMail" :onForward="forwardMail" :onSaveToS3="saveToS3Proxy" />
          </n-card>
          <n-card :bordered="false" embedded class="mail-item mailbox-empty" v-else>
            <n-result status="info" :title="count === 0 ? t('emptyInbox') : t('pleaseSelectMail')">
              <template #icon>
                <n-icon :component="InboxRound" :size="56" />
              </template>
            </n-result>
          </n-card>
        </template>
      </n-split>
      <div v-else class="mail-list-scroll mailbox-full-list">
        <n-list class="mailbox-list" hoverable clickable>
          <n-list-item v-for="row in data" v-bind:key="row.id" @click="() => clickRow(row)"
            :class="['mailbox-row', 'mailbox-row--preview', mailItemClass(row)]">
            <template #prefix v-if="multiActionMode">
              <n-checkbox v-model:checked="row.checked" />
            </template>
            <n-thing class="mail-list-thing">
              <template #header>
                <n-ellipsis class="mail-list-title">
                  {{ row.subject }}
                </n-ellipsis>
              </template>
              <template #header-extra>
                <span class="mailbox-row__date">{{ utcToLocalDate(row.created_at, useUTCDate) }}</span>
              </template>
              <template #description>
                <div class="mail-list-meta mailbox-row__meta">
                  <span class="mailbox-row__sender">
                    <n-ellipsis class="mail-list-meta-text">
                      {{ showEMailTo ? "FROM: " + row.source : row.source }}
                    </n-ellipsis>
                  </span>
                  <span class="mailbox-row__id">#{{ row.id }}</span>
                  <span v-if="showEMailTo" class="mailbox-row__recipient">
                    <n-ellipsis class="mail-list-meta-text">
                      TO: {{ row.address }}
                    </n-ellipsis>
                  </span>
                  <AiExtractInfo :metadata="row.metadata" compact />
                </div>
              </template>
              <n-ellipsis v-if="row.text && mailListPreviewLineClampValue > 0"
                :line-clamp="mailListPreviewLineClampValue" class="mail-list-preview" :tooltip="false">
                {{ row.text }}
              </n-ellipsis>
            </n-thing>
          </n-list-item>
        </n-list>
      </div>
    </div>
    <div class="mailbox-mobile" v-else>
      <n-space class="mobile-toolbar" justify="space-between" align="center" :wrap="false">
        <n-pagination v-model:page="page" v-model:page-size="pageSize" :item-count="count" simple size="small" />
        <n-switch v-model:value="autoRefresh" size="small" :round="false">
          <template #checked>
            {{ t('refreshAfter', { msg: autoRefreshInterval }) }}
          </template>
          <template #unchecked>
            {{ t('autoRefresh') }}
          </template>
        </n-switch>
        <n-button @click="backFirstPageAndRefresh" tertiary size="small" type="primary">
          {{ t('refresh') }}
        </n-button>
      </n-space>
      <div v-if="showFilterInput" class="mobile-search">
        <n-input v-model:value="localFilterKeyword"
          :placeholder="t('keywordQueryTip')" size="small" clearable />
      </div>
      <div class="mobile-list-pane">
        <n-list class="mailbox-list" hoverable clickable>
          <n-list-item class="mailbox-row" v-for="row in data" v-bind:key="row.id" @click="() => clickRow(row)">
            <n-thing class="mailbox-row__content">
              <template #header>
                <n-ellipsis class="mailbox-row__subject">{{ row.subject }}</n-ellipsis>
              </template>
              <template #header-extra>
                <span class="mailbox-row__date">{{ utcToLocalDate(row.created_at, useUTCDate) }}</span>
              </template>
              <template #description>
                <div class="mailbox-row__meta">
                  <span class="mailbox-row__sender">
                    <n-ellipsis>
                    {{ showEMailTo ? "FROM: " + row.source : row.source }}
                    </n-ellipsis>
                  </span>
                  <span class="mailbox-row__id">#{{ row.id }}</span>
                  <span v-if="showEMailTo" class="mailbox-row__recipient">
                    <n-ellipsis>TO: {{ row.address }}</n-ellipsis>
                  </span>
                  <AiExtractInfo :metadata="row.metadata" compact />
                </div>
              </template>
            </n-thing>
          </n-list-item>
        </n-list>
      </div>
      <n-drawer v-model:show="curMail" width="100%" placement="bottom" :trap-focus="false" :block-scroll="false"
        style="height: 80vh;">
        <n-drawer-content :title="curMail ? curMail.subject : ''" closable>
          <n-card class="mobile-message-card" :bordered="false" embedded>
            <MailContentRenderer :mail="curMail" :showEMailTo="showEMailTo"
              :enableUserDeleteEmail="enableUserDeleteEmail" :showReply="showReply" :showSaveS3="showSaveS3"
              :useUTCDate="useUTCDate" :onDelete="deleteMail" :onReply="replyMail" :onForward="forwardMail"
              :onSaveToS3="saveToS3Proxy" />
          </n-card>
        </n-drawer-content>
      </n-drawer>
    </div>
    <n-modal v-model:show="showMultiActionDownload" preset="dialog" :title="t('downloadMail')">
      <n-tag type="info">
        {{ multiActionDownloadZip.filename }}
      </n-tag>
      <n-button tag="a" target="_blank" tertiary type="info" size="small" :download="multiActionDownloadZip.filename"
        :href="multiActionDownloadZip.url">
        <n-icon :component="CloudDownloadRound" />
        {{ t('downloadMail') + " zip" }}
      </n-button>
    </n-modal>
    <n-modal v-model:show="showMultiActionDelete" preset="dialog" :title="t('delete') + t('success')"
      negative-text="OK">
      <n-space justify="center">
        <n-progress type="circle" status="error" :percentage="multiActionDeleteProgress.percentage">
          <span style="text-align: center">
            {{ multiActionDeleteProgress.tip }}
          </span>
        </n-progress>
      </n-space>
    </n-modal>
  </section>
</template>

<style scoped>
.mailbox-desktop,
.mailbox-mobile {
  text-align: left;
}

.center {
  text-align: center;
}

.overlay {
  width: 100%;
}

.overlay-dark-backgroud {
  background-color: var(--app-accent-soft) !important;
}

.overlay-light-backgroud {
  background-color: var(--app-accent-soft) !important;
}

.mail-item {
  height: 100%;
}

.mail-list-scroll {
  overflow-y: auto;
  overflow-x: hidden;
}

.mail-list-thing,
.mail-list-title,
.mail-list-preview {
  min-width: 0;
  max-width: 100%;
}

.mail-list-thing,
.mail-list-preview {
  width: 100%;
}

.mail-list-thing :deep(.n-thing-main),
.mail-list-thing :deep(.n-thing-header),
.mail-list-thing :deep(.n-thing-header__title),
.mail-list-thing :deep(.n-thing-main__description),
.mail-list-thing :deep(.n-thing-main__content) {
  min-width: 0;
}

.mail-list-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  min-width: 0;
  max-width: 100%;
}

.mail-list-meta-text {
  max-width: min(240px, 100%);
}

.mail-list-preview {
  display: -webkit-box;
  overflow-wrap: anywhere;
  opacity: 0.7;
}

.mail-list-scroll :deep(.n-list-item__main) {
  min-width: 0;
}

pre {
  white-space: pre-wrap;
  word-wrap: break-word;
}

.split-handle {
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.split-handle__grip {
  width: 3px;
  height: 36px;
  border-radius: 2px;
  background-color: var(--app-border-strong);
  transition: background-color 0.2s;
}

.split-handle:hover .split-handle__grip {
  background-color: var(--app-accent);
}
</style>

// frontend/src/features/mail/mailbox.tsx
import { useEffect, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Group, Panel, Separator as ResizeHandle } from 'react-resizable-panels'
import JSZip from 'jszip'
import { ChevronLeft, ChevronRight, Download, Inbox, RefreshCw, Search, SquareCheckBig, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { confirmAction } from '@/components/action-dialogs'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { processItem } from '@/utils/email-parser'
import { buildForwardModel, buildReplyModel } from '@/utils/mail-actions'
import { appStore, useAppStore } from '@/lib/store'
import { downloadBlob, formatDate, stringifyError } from '@/lib/utils'
import { useScopedI18n } from '@/i18n/react'
import { AiExtract } from './ai-extract'
import { MailContent, type MailItem } from './mail-content'

type Props = {
  queryKey: unknown[]
  fetchMailData: (limit: number, offset: number) => Promise<{ results: any[]; count: number }>
  deleteMail?: (id: number | string) => Promise<any>
  canDelete?: boolean
  showEmailTo?: boolean
  showReply?: boolean
  showSaveS3?: boolean
  saveToS3?: (id: number | string, filename: string, blob: Blob) => Promise<any>
  showFilter?: boolean
}

export function Mailbox({ queryKey, fetchMailData, deleteMail, canDelete, showEmailTo = true, showReply, showSaveS3, saveToS3, showFilter }: Props) {
  const { t } = useScopedI18n('components.MailBox')
  const state = useAppStore((value) => ({ autoRefresh: value.autoRefresh, interval: value.configAutoRefreshInterval, useUTC: value.useUTCDate, split: value.mailboxSplitSize, wideList: value.mailListView, preview: value.mailListPreviewLineClamp }))
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [filter, setFilter] = useState('')
  const [selectedMail, setSelectedMail] = useState<MailItem | null>(null)
  const [multi, setMulti] = useState(false)
  const [checked, setChecked] = useState<Set<string>>(new Set())
  const [mobileDetail, setMobileDetail] = useState(false)
  const query = useQuery({
    queryKey: [...queryKey, page, pageSize],
    queryFn: async () => { const result = await fetchMailData(pageSize, (page - 1) * pageSize); return { count: result.count || 0, results: await Promise.all((result.results || []).map((item) => processItem({ ...item }))) as MailItem[] } },
    refetchInterval: state.autoRefresh ? state.interval * 1000 : false,
  })
  const data = useMemo(() => {
    const keyword = filter.trim().toLowerCase()
    return keyword ? (query.data?.results || []).filter((item) => [item.subject, item.text, item.message].some((value) => String(value || '').toLowerCase().includes(keyword))) : query.data?.results || []
  }, [filter, query.data?.results])
  const count = query.data?.count || 0
  const maxPage = Math.max(1, Math.ceil(count / pageSize))
  useEffect(() => { if (selectedMail && !data.some((item) => item.id === selectedMail.id)) setSelectedMail(null) }, [data, selectedMail])

  const choose = (mail: MailItem) => { if (multi) { setChecked((current) => { const next = new Set(current); const id = String(mail.id); next.has(id) ? next.delete(id) : next.add(id); return next }) } else { setSelectedMail(mail); if (innerWidth < 768) setMobileDetail(true) } }
  const removeOne = async () => { if (!selectedMail || !deleteMail) return; try { await deleteMail(selectedMail.id); setSelectedMail(null); await query.refetch(); toast.success(t('success')) } catch (error) { toast.error(stringifyError(error)) } }
  const removeSelected = async () => { if (!deleteMail || !checked.size) return toast.error(t('pleaseSelectMail')); if (!(await confirmAction({ title: t('delete'), description: t('deleteMailTip'), destructive: true }))) return; try { for (const item of data.filter((mail) => checked.has(String(mail.id)))) await deleteMail(item.id); setChecked(new Set()); await query.refetch(); toast.success(t('success')) } catch (error) { toast.error(stringifyError(error)) } }
  const downloadSelected = async () => { if (!checked.size) return toast.error(t('pleaseSelectMail')); const zip = new JSZip(); data.filter((mail) => checked.has(String(mail.id))).forEach((mail) => zip.file(`${mail.id}.eml`, mail.raw || '')); downloadBlob(await zip.generateAsync({ type: 'blob' }), `mails-${new Date().toISOString().replaceAll(':', '-')}.zip`) }
  const reply = () => { if (!selectedMail) return; appStore.setState((current) => ({ sendMailModel: { ...current.sendMailModel, ...buildReplyModel(selectedMail, t('reply')) }, indexTab: 'sendmail' })) }
  const forward = () => { if (!selectedMail) return; appStore.setState((current) => ({ sendMailModel: { ...current.sendMailModel, ...buildForwardModel(selectedMail, t('forwardMail')) }, indexTab: 'sendmail' })) }

  const toolbar = <div className="flex min-h-12 flex-wrap items-center gap-2 border-b border-border px-3 py-1.5">
    {multi ? <><Button variant="ghost" onClick={() => { setMulti(false); setChecked(new Set()) }}>{t('cancelMultiAction')}</Button><Button variant="ghost" onClick={() => setChecked(new Set(data.map((item) => String(item.id))))}>{t('selectAll')}</Button><Button variant="ghost" onClick={() => setChecked(new Set())}>{t('unselectAll')}</Button>{canDelete && <Button variant="ghost" className="text-destructive" onClick={removeSelected}><Trash2 />{t('delete')}</Button>}<Button variant="ghost" onClick={downloadSelected}><Download />{t('downloadMail')}</Button></> : <>
      <Button variant="ghost" onClick={() => setMulti(true)}><SquareCheckBig />{t('multiAction')}</Button>
      <Button variant="outline" size="icon" title="Previous page" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft /></Button><span className="numeric grid h-9 min-w-9 place-items-center rounded-md border border-border px-2">{page}</span><Button variant="outline" size="icon" title="Next page" disabled={page >= maxPage} onClick={() => setPage((value) => value + 1)}><ChevronRight /></Button>
      <Select value={String(pageSize)} onValueChange={(value) => { setPageSize(Number(value)); setPage(1) }}><SelectTrigger className="w-[88px]"><SelectValue /></SelectTrigger><SelectContent>{[20, 50, 100].map((value) => <SelectItem key={value} value={String(value)}>{value} / {t('page') || 'page'}</SelectItem>)}</SelectContent></Select>
      <label className="flex h-9 items-center gap-2 rounded-md px-2 text-xs text-muted-foreground"><Switch checked={state.autoRefresh} onCheckedChange={(value) => appStore.setState({ autoRefresh: value })} />{t('autoRefresh')}</label>
      <Button variant="secondary" onClick={() => { setPage(1); query.refetch() }}><RefreshCw className={query.isFetching ? 'animate-spin' : ''} />{t('refresh')}</Button>
      {showFilter && <div className="relative min-w-48 flex-1 sm:max-w-72"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-9 min-h-9 pl-9" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder={t('keywordQueryTip')} /></div>}
    </>}
  </div>

  const list = <div role="list" className="h-full overflow-auto">{query.isLoading ? Array.from({ length: 7 }).map((_, index) => <div key={index} className="h-[76px] animate-pulse border-b border-border bg-transparent" />) : data.length ? data.map((mail) => <button type="button" role="listitem" key={mail.id} className={`grid w-full gap-1 border-b border-border px-3 py-2.5 text-left hover:bg-muted/50 ${selectedMail?.id === mail.id ? 'bg-accent' : ''}`} onClick={() => choose(mail)}>
    <span className="flex min-w-0 items-center gap-2">{multi && <Checkbox checked={checked.has(String(mail.id))} tabIndex={-1} />}<strong className="min-w-0 flex-1 truncate text-sm font-semibold">{mail.subject || t('noSubject')}</strong><time className="numeric shrink-0 text-[11px] text-muted-foreground">{formatDate(mail.created_at, state.useUTC)}</time></span>
    <span className="flex min-w-0 items-center gap-2 text-xs text-muted-foreground"><span className="min-w-0 flex-1 truncate">{showEmailTo ? 'FROM: ' : ''}{mail.source}</span>{showEmailTo && <span className="hidden max-w-36 truncate xl:block">TO: {mail.address}</span>}<span className="numeric">#{mail.id}</span></span>
    {state.preview > 0 && mail.text && <span className="overflow-hidden text-xs text-muted-foreground/80" style={{ display: '-webkit-box', WebkitBoxOrient: 'vertical', WebkitLineClamp: state.preview }}>{mail.text}</span>}<AiExtract metadata={mail.metadata} compact />
  </button>) : <div className="grid h-full min-h-72 place-items-center text-center text-muted-foreground"><div><Inbox className="mx-auto mb-3 size-10 stroke-1" /><p className="text-sm">{t('emptyInbox')}</p></div></div>}</div>

  const detail = selectedMail ? <div className="h-full overflow-auto"><div className="border-b border-border px-5 py-3"><h1 className="truncate text-base font-semibold">{selectedMail.subject}</h1></div><MailContent mail={selectedMail} showEmailTo={showEmailTo} canDelete={canDelete} showReply={showReply} showSaveS3={showSaveS3} onDelete={removeOne} onReply={reply} onForward={forward} onSaveToS3={saveToS3 ? (filename, blob) => saveToS3(selectedMail.id, filename, blob) : undefined} /></div> : <div className="grid h-full place-items-center text-center text-muted-foreground"><div><Inbox className="mx-auto mb-3 size-12 stroke-1" /><p>{count ? t('pleaseSelectMail') : t('emptyInbox')}</p></div></div>

  return <div className="flex h-full min-h-0 flex-col bg-background">{toolbar}<div className="min-h-0 flex-1"><div className="hidden h-full md:block">{state.wideList && !selectedMail ? list : <Group orientation="horizontal" className="h-full" defaultLayout={{ list: Math.round(state.split * 100), detail: Math.round((1 - state.split) * 100) }} onLayoutChanged={(layout) => appStore.setState({ mailboxSplitSize: (layout.list || 32) / 100 })}><Panel id="list" minSize="20%" defaultSize={`${Math.round(state.split * 100)}%`}>{list}</Panel><ResizeHandle className="group relative w-px bg-border outline-none"><span className="absolute inset-y-0 -left-1 w-2 group-hover:bg-primary/10" /></ResizeHandle><Panel id="detail" minSize="25%">{detail}</Panel></Group>}</div><div className="h-full md:hidden">{list}</div></div>
    <Dialog open={mobileDetail} onOpenChange={setMobileDetail}><DialogContent className="h-[calc(100dvh-16px)] w-[calc(100vw-16px)] max-w-none p-0" showClose>{detail}</DialogContent></Dialog>
  </div>
}
