// frontend/src/features/user/user-settings.tsx
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { startRegistration } from '@simplewebauthn/browser'
import { KeyRound, LogOut, Pencil, Plus, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { confirmAction } from '@/components/action-dialogs'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { SettingsLayout } from '@/components/layout/settings-layout'
import { api } from '@/lib/api'
import { appStore } from '@/lib/store'
import { formatDate, stringifyError } from '@/lib/utils'
import { useScopedI18n } from '@/i18n/react'

export function UserSettingsPage() {
  const { t } = useScopedI18n('views.user.UserSettings')
  const [createOpen, setCreateOpen] = useState(false), [renameOpen, setRenameOpen] = useState(false), [listOpen, setListOpen] = useState(false), [logoutOpen, setLogoutOpen] = useState(false)
  const [name, setName] = useState(''), [current, setCurrent] = useState<any>(null)
  const passkeys = useQuery({ queryKey: ['passkeys'], queryFn: () => api.fetch<any[]>('/user_api/passkey'), enabled: listOpen })
  const create = async () => { try { const options = await api.fetch<any>('/user_api/passkey/register_request', { method: 'POST', body: { domain: location.hostname } }); const credential = await startRegistration({ optionsJSON: options }); await api.fetch('/user_api/passkey/register_response', { method: 'POST', body: { origin: location.origin, passkey_name: name || `${navigator.platform || 'Unknown'}: ${Math.random().toString(36).slice(7)}`, credential } }); toast.success(t('passkeyCreated')); setName(''); setCreateOpen(false); if (listOpen) await passkeys.refetch() } catch (error) { toast.error(stringifyError(error)) } }
  const rename = async () => { try { await api.fetch('/user_api/passkey/rename', { method: 'POST', body: { passkey_name: name, passkey_id: current.passkey_id } }); await passkeys.refetch(); setRenameOpen(false); setName('') } catch (error) { toast.error(stringifyError(error)) } }
  const remove = async (id: string) => { if (!(await confirmAction({ title: t('deletePasskey'), destructive: true }))) return; try { await api.fetch(`/user_api/passkey/${id}`, { method: 'DELETE' }); await passkeys.refetch() } catch (error) { toast.error(stringifyError(error)) } }
  const logout = () => { appStore.resetUser(); location.reload() }
  return <SettingsLayout><div className="grid gap-2"><Button className="justify-start" variant="secondary" onClick={() => { setListOpen(true); passkeys.refetch() }}><KeyRound />{t('showPasskeyList')}</Button><Button className="justify-start" variant="secondary" onClick={() => setCreateOpen(true)}><Plus />{t('createPasskey')}</Button><p className="rounded-md bg-muted p-3 text-sm text-muted-foreground">{t('passordTip')}</p><Button className="justify-start" variant="secondary" onClick={() => setLogoutOpen(true)}><LogOut />{t('logout')}</Button></div>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>{t('createPasskey')}</DialogTitle></DialogHeader><Input value={name} placeholder={t('passkeyNamePlaceholder')} onChange={(event) => setName(event.target.value)} /><DialogFooter><Button onClick={create}><Plus />{t('createPasskey')}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>{t('renamePasskey')}</DialogTitle></DialogHeader><Input value={name} placeholder={t('renamePasskeyNamePlaceholder')} onChange={(event) => setName(event.target.value)} /><DialogFooter><Button onClick={rename}><Pencil />{t('renamePasskey')}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={listOpen} onOpenChange={setListOpen}><DialogContent className="w-[min(820px,calc(100vw-32px))]"><DialogHeader><DialogTitle>{t('showPasskeyList')}</DialogTitle></DialogHeader><Table><TableHeader><TableRow><TableHead>Passkey ID</TableHead><TableHead>{t('passkey_name')}</TableHead><TableHead>{t('created_at')}</TableHead><TableHead>{t('actions')}</TableHead></TableRow></TableHeader><TableBody>{(passkeys.data || []).map((row) => <TableRow key={row.passkey_id}><TableCell className="numeric max-w-48 truncate text-xs">{row.passkey_id}</TableCell><TableCell>{row.passkey_name}</TableCell><TableCell className="numeric text-xs">{formatDate(row.created_at)}</TableCell><TableCell><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => { setCurrent(row); setName(row.passkey_name || ''); setRenameOpen(true) }}><Pencil /></Button><Button size="icon" variant="ghost" className="text-destructive" onClick={() => remove(row.passkey_id)}><Trash2 /></Button></div></TableCell></TableRow>)}</TableBody></Table></DialogContent></Dialog>
    <Dialog open={logoutOpen} onOpenChange={setLogoutOpen}><DialogContent><DialogHeader><DialogTitle>{t('logout')}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{t('logoutConfirm')}</p><DialogFooter><Button onClick={logout}><LogOut />{t('logout')}</Button></DialogFooter></DialogContent></Dialog>
  </SettingsLayout>
}

// frontend/src/views/user/UserSettings.vue
<script setup>
import { ref } from 'vue'
import { useScopedI18n } from '@/i18n/app'
import { startRegistration } from '@simplewebauthn/browser';
import { NButton, NPopconfirm } from 'naive-ui'

import { useGlobalState } from '../../store'
import { api } from '../../api'

const { userJwt, userSettings, } = useGlobalState()
const message = useMessage()

const showLogout = ref(false)
const showCreatePasskey = ref(false)
const passkeyName = ref('')
const showPasskeyList = ref(false)
const showRenamePasskey = ref(false)
const currentPasskeyId = ref(null)
const currentPasskeyName = ref('')

const { t } = useScopedI18n('views.user.UserSettings')


const logout = async () => {
    userJwt.value = '';
    location.reload()
}

const createPasskey = async () => {
    try {
        const options = await api.fetch(`/user_api/passkey/register_request`, {
            method: 'POST',
            body: JSON.stringify({
                domain: location.hostname,
            })
        })
        const credential = await startRegistration({ optionsJSON: options })

        // Send the result to the server and return the promise.
        await api.fetch(`/user_api/passkey/register_response`, {
            method: 'POST',
            body: JSON.stringify({
                origin: location.origin,
                passkey_name: passkeyName.value || (
                    (window.navigator.userAgentData?.platform || "Unknown")
                    + ": " + Math.random().toString(36).substring(7)
                ),
                credential
            })
        })
        message.success(t('passkeyCreated'));
    } catch (e) {
        console.error(e)
        message.error(e.message)
    } finally {
        passkeyName.value = ''
        showCreatePasskey.value = false
    }
}

const passkeyColumns = [
    {
        title: "Passkey ID",
        key: "passkey_id"
    },
    {
        title: t('passkey_name'),
        key: "passkey_name"
    },
    {
        title: t('created_at'),
        key: "created_at"
    },
    {
        title: t('updated_at'),
        key: "updated_at"
    },
    {
        title: t('actions'),
        key: 'actions',
        render(row) {
            return h('div', [
                [
                    h(NButton,
                        {
                            tertiary: true,
                            type: "primary",
                            onClick: () => {
                                showRenamePasskey.value = true;
                                currentPasskeyId.value = row.passkey_id;
                            }
                        },
                        { default: () => t('renamePasskey') }
                    ),
                    h(NPopconfirm,
                        {
                            onPositiveClick: async () => {
                                try {
                                    await api.fetch(`/user_api/passkey/${row.passkey_id}`, {
                                        method: 'DELETE'
                                    })
                                    await fetchPasskeyList()
                                } catch (e) {
                                    console.error(e)
                                    message.error(e.message)
                                }
                            }
                        },
                        {
                            trigger: () => h(NButton,
                                {
                                    tertiary: true,
                                    type: "error",
                                },
                                { default: () => t('deletePasskey') }
                            ),
                            default: () => `${t('deletePasskey')}?`
                        }
                    ),
                ]
            ])
        }
    }
]

const passkeyData = ref([])

const fetchPasskeyList = async () => {
    try {
        const data = await api.fetch(`/user_api/passkey`)
        passkeyData.value = data
    } catch (e) {
        console.error(e)
        message.error(e.message)
    }
}

const renamePasskey = async () => {
    try {
        await api.fetch(`/user_api/passkey/rename`, {
            method: 'POST',
            body: JSON.stringify({
                passkey_name: currentPasskeyName.value,
                passkey_id: currentPasskeyId.value
            })
        })
        await fetchPasskeyList()
    } catch (e) {
        console.error(e)
        message.error(e.message)
    } finally {
        currentPasskeyName.value = ''
        showRenamePasskey.value = false
    }
}
</script>

<template>
    <div class="center" v-if="userSettings.user_email">
        <n-card class="settings-card" :bordered="false" embedded>
            <n-button @click="showPasskeyList = true; fetchPasskeyList();" secondary block strong>
                {{ t('showPasskeyList') }}
            </n-button>
            <n-button @click="showCreatePasskey = true" type="primary" secondary block strong>
                {{ t('createPasskey') }}
            </n-button>
            <n-alert :show-icon="false" :bordered="false">
                <span>
                    {{ t('passordTip') }}
                </span>
            </n-alert>
            <n-button @click="showLogout = true" secondary block strong>
                {{ t('logout') }}
            </n-button>
        </n-card>
        <n-modal v-model:show="showCreatePasskey" preset="dialog" :title="t('createPasskey')">
            <n-input v-model:value="passkeyName" :placeholder="t('passkeyNamePlaceholder')" />
            <template #action>
                <n-button :loading="loading" @click="createPasskey" size="small" tertiary type="primary">
                    {{ t('createPasskey') }}
                </n-button>
            </template>
        </n-modal>
        <n-modal v-model:show="showRenamePasskey" preset="dialog" :title="t('renamePasskey')">
            <n-input v-model:value="currentPasskeyName" :placeholder="t('renamePasskeyNamePlaceholder')" />
            <template #action>
                <n-button :loading="loading" @click="renamePasskey" size="small" tertiary type="primary">
                    {{ t('renamePasskey') }}
                </n-button>
            </template>
        </n-modal>
        <n-modal v-model:show="showPasskeyList" preset="card" :title="t('showPasskeyList')">
            <n-data-table :columns="passkeyColumns" :data="passkeyData" :bordered="false" embedded />
        </n-modal>
        <n-modal v-model:show="showLogout" preset="dialog" :title="t('logout')">
            <p>{{ t('logoutConfirm') }}</p>
            <template #action>
                <n-button :loading="loading" @click="logout" size="small" tertiary type="warning">
                    {{ t('logout') }}
                </n-button>
            </template>
        </n-modal>
    </div>
</template>

<style scoped>
.center {
    display: flex;
    justify-content: center;
}


.n-card {
    max-width: 800px;
    text-align: left;
}

.n-button {
    margin-top: 10px;
    margin-bottom: 10px;
}
</style>
